version: "3"
services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - NODE_ENV=development
      - RAILS_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - postgres
volumes:
  postgresdata:
