default: &default
  adapter: postgresql
  endcoding: utf8
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: GA_PROJ_dev

test: &test
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: GA_PROJ_test

production:
  <<: *default
  database: GA_PROJ_prod
